Vagrant.configure(2) do |config|

  config.ssh.insert_key = false
  config.ssh.username = "vagrant"

  config.vm.network "private_network", ip: "192.168.50.4"
  config.vm.define "01-webappservers" do |vagrant2|
    vagrant2.vm.box = "ubuntu/trusty64"
    vagrant2.vm.network "forwarded_port", guest:   80, host: 80
    vagrant2.vm.network "forwarded_port", guest:  443, host: 443
  end


  config.vm.synced_folder "/tmp", "/tmp/foo"
  
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
  end
    
  config.vm.provision "ansible" do |ansible|
    ansible.limit = "all"
    ansible.playbook = "vagrant.yml"
# using inventory path disables Vagrant dynamic inventory    
#    ansible.inventory_path = "../env/vagrant"
    ansible.extra_vars = {
     "inventory" => "vagrant",
     "a_env_variable" => "My awesome env variable"
    }

    ansible.groups = {
      "webappservers" => ["01-webappservers"],
      "all_groups:children" => ["webappservers"]
    }
    ansible.raw_arguments  = "--user=vagrant"
    ansible.raw_arguments  = "--vault-password-file=../ansible/ansible-vault-password.yml"
  end
end
